name: SST deploy workflow
on: 
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy SST APP
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: "./"

      - name: Use Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_DEPLOY_ROLE }}
      
      - name: Deploy app
        run: npx sst deploy --stage prod


# name: SST workflow
# on: push

# # Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
# concurrency:
#   group: merge-${{ github.ref }}

# permissions:
#   id-token: write # This is required for requesting the JWT
#   contents: read # This is required for actions/checkout

# jobs:
#   DeployApp:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Git clone the repository
#         uses: actions/checkout@v3
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v3
#         with:
#           role-to-assume: arn:aws:iam::400325002411:role/GitHub
#           aws-region: ap-southeast-2
#       - name: Deploy app
#         run: |
#           npx sst deploy --stage prod